### ISSUE TITLE
add to babel-loader webpack config for es5 compilation

### ISSUE THREAD

**Issue by cthorner** [sindresorhus/url-parse-lax#3]
I had to do this in my webpack config to get this working on IE:
```js
{
        test: /\.js$/,
        exclude: /node_modules\/(?:(?!url-parse-lax)(?!prepend-http))/,
        use: ['babel-loader']
}
```
Just leaving it here in case someone else runs into the same issue.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
